version: "latest"

services:
  database:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKER_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./.docker/volumes/database:/data/db
